zuul:
  routes:
    add-service:
      path: /add/**
      serviceId: add-service
    edit-service1:
      path: /edit/**
      url: http://localhost:8082

loggin:
  level:
    org.springframework.boot: DEBUG