spring:
  application:
     name: edit-service
  thymeleaf:
    mode: LEGACYHTML5

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8082   # HTTP (Tomcat) port
  contextPath: /test1/test2