spring:
  application:
     name: spring-config
  cloud:
     config:
       server:
         native:
           searchLocations: classpath:/config

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port